const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  clientes:        ()      => ipcRenderer.invoke('clientes'),
  configLeer:      ()      => ipcRenderer.invoke('config-leer'),
  configGuardar:   (d)     => ipcRenderer.invoke('config-guardar', d),
  marcaVista:      ()      => ipcRenderer.invoke('marca-vista'),
  marcaElegirLogo: ()      => ipcRenderer.invoke('marca-elegir-logo'),
  marcaQuitarLogo: ()      => ipcRenderer.invoke('marca-quitar-logo'),
  motoresEstado:   ()      => ipcRenderer.invoke('motores-estado'),
  motorProbar:     (id)    => ipcRenderer.invoke('motor-probar', id),
  guardarLlave:    (d)     => ipcRenderer.invoke('guardar-llave', d),
  diagnostico:     ()      => ipcRenderer.invoke('diagnostico'),
  ejemploInstalar: ()      => ipcRenderer.invoke('ejemplo-instalar'),
  diagnosticoTexto:()      => ipcRenderer.invoke('diagnostico-texto'),
  diagnosticoCopiar:(t)    => ipcRenderer.invoke('diagnostico-copiar', t),

  redaccionFalta:  ()      => ipcRenderer.invoke('redaccion-falta'),
  micros:          ()      => ipcRenderer.invoke('micros'),
  soportaMicrofono:()      => ipcRenderer.invoke('soporta-microfono'),
  descargarModelo: ()      => ipcRenderer.invoke('descargar-modelo'),
  instalarDep:     (f)     => ipcRenderer.invoke('instalar-dependencia', f),
  instalarOllama:  ()      => ipcRenderer.invoke('instalar-ollama'),
  abrirExterno:    (u)     => ipcRenderer.invoke('abrir-externo', u),
  onDescarga:      (cb)    => ipcRenderer.on('descarga', (_e, d) => cb(d)),
  onInstalando:    (cb)    => ipcRenderer.on('instalando', (_e, d) => cb(d)),
  reuniones:       (slug)  => ipcRenderer.invoke('reuniones', slug),
  pendientes:      (slug)  => ipcRenderer.invoke('pendientes', slug),
  crearCliente:    (d)     => ipcRenderer.invoke('crear-cliente', d),
  expedientes:     ()      => ipcRenderer.invoke('expedientes'),
  enlazarExpediente:(d)    => ipcRenderer.invoke('enlazar-expediente', d),
  grabarIniciar:   (slug, op) => ipcRenderer.invoke('grabar-iniciar', slug, op || {}),
  grabarDetener:   ()      => ipcRenderer.invoke('grabar-detener'),
  procesar:        (d)     => ipcRenderer.invoke('procesar', d),
  cancelarProceso: ()      => ipcRenderer.invoke('cancelar-proceso'),
  procesoEnCurso:  ()      => ipcRenderer.invoke('proceso-en-curso'),
  eliminarReunion: (d)     => ipcRenderer.invoke('eliminar-reunion', d),
  elegirCarpeta:   (a)     => ipcRenderer.invoke('elegir-carpeta', a),
  guardarMinuta:   (d)     => ipcRenderer.invoke('guardar-minuta', d),
  pdf:             (d)     => ipcRenderer.invoke('pdf', d),
  copiarMinuta:    (t)     => ipcRenderer.invoke('copiar-minuta', t),
  compromisos:     (d)     => ipcRenderer.invoke('compromisos', d),
  marcarCompromiso:(d)     => ipcRenderer.invoke('compromiso-marcar', d),
  copiarTexto:     (t)     => ipcRenderer.invoke('copiar-texto', t),
  guardarComo:     (d)     => ipcRenderer.invoke('guardar-como', d),
  compartir:       (d)     => ipcRenderer.invoke('compartir', d),
  abrirPermisos:   ()      => ipcRenderer.invoke('abrir-permisos'),
  preparar:        (d)     => ipcRenderer.invoke('preparar', d),
  preparacionLeer: (d)     => ipcRenderer.invoke('preparacion-leer', d),
  preparacionPdf:  (d)     => ipcRenderer.invoke('preparacion-pdf', d),
  abrir:           (r)     => ipcRenderer.invoke('abrir', r),
  revelar:         (r)     => ipcRenderer.invoke('revelar', r),
  importar:        ()      => ipcRenderer.invoke('importar'),
  importarACarpeta:(d)     => ipcRenderer.invoke('importar-a-carpeta', d),
  buscar:          (t)     => ipcRenderer.invoke('buscar', t),
  exportarHistorial:(d)    => ipcRenderer.invoke('exportar-historial', d),
  onProgreso:      (cb)    => ipcRenderer.on('progreso', (_e, d) => cb(d)),
  onNiveles:       (cb)    => ipcRenderer.on('niveles', (_e, d) => cb(d)),
  onCapturaAviso:  (cb)    => ipcRenderer.on('captura-aviso', (_e, d) => cb(d)),
  clienteActivo:   (c)     => ipcRenderer.invoke('cliente-activo', c),
  onAtajo:         (cb)    => ipcRenderer.on('atajo', (_e, d) => cb(d)),
  onMenu:          (cb)    => ipcRenderer.on('menu', (_e, d) => cb(d)),
  onAvisoArranque: (cb)    => ipcRenderer.on('aviso-arranque', (_e, d) => cb(d)),
  onAvisoBreve:    (cb)    => ipcRenderer.on('aviso-breve', (_e, d) => cb(d)),
});
