const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  clientes:        ()      => ipcRenderer.invoke('clientes'),
  configLeer:      ()      => ipcRenderer.invoke('config-leer'),
  configGuardar:   (d)     => ipcRenderer.invoke('config-guardar', d),
  motoresEstado:   ()      => ipcRenderer.invoke('motores-estado'),
  motorProbar:     (id)    => ipcRenderer.invoke('motor-probar', id),
  guardarLlave:    (d)     => ipcRenderer.invoke('guardar-llave', d),
  diagnostico:     ()      => ipcRenderer.invoke('diagnostico'),
  descargarModelo: ()      => ipcRenderer.invoke('descargar-modelo'),
  instalarDep:     (f)     => ipcRenderer.invoke('instalar-dependencia', f),
  onDescarga:      (cb)    => ipcRenderer.on('descarga', (_e, d) => cb(d)),
  onInstalando:    (cb)    => ipcRenderer.on('instalando', (_e, d) => cb(d)),
  reuniones:       (slug)  => ipcRenderer.invoke('reuniones', slug),
  crearCliente:    (n)     => ipcRenderer.invoke('crear-cliente', n),
  grabarIniciar:   (slug)  => ipcRenderer.invoke('grabar-iniciar', slug),
  grabarDetener:   ()      => ipcRenderer.invoke('grabar-detener'),
  procesar:        (d)     => ipcRenderer.invoke('procesar', d),
  guardarMinuta:   (d)     => ipcRenderer.invoke('guardar-minuta', d),
  pdf:             (d)     => ipcRenderer.invoke('pdf', d),
  abrir:           (r)     => ipcRenderer.invoke('abrir', r),
  revelar:         (r)     => ipcRenderer.invoke('revelar', r),
  importar:        ()      => ipcRenderer.invoke('importar'),
  importarACarpeta:(d)     => ipcRenderer.invoke('importar-a-carpeta', d),
  buscar:          (t)     => ipcRenderer.invoke('buscar', t),
  exportarHistorial:(d)    => ipcRenderer.invoke('exportar-historial', d),
  onProgreso:      (cb)    => ipcRenderer.on('progreso', (_e, d) => cb(d)),
  onNiveles:       (cb)    => ipcRenderer.on('niveles', (_e, d) => cb(d)),
  clienteActivo:   (c)     => ipcRenderer.invoke('cliente-activo', c),
  onAtajo:         (cb)    => ipcRenderer.on('atajo', (_e, d) => cb(d)),
});
